[package]
name = "imgui-gfx-renderer"
version = "0.8.0"
edition = "2018"
authors = ["The imgui-rs Developers"]
description = "gfx renderer for the imgui crate"
homepage = "https://github.com/imgui-rs/imgui-rs"
repository = "https://github.com/imgui-rs/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "rendering"]

[features]
opengl = []
directx = []
default = ["opengl"]

[badges]
maintenance = { status = "deprecated" }

[dependencies]
gfx = "0.18"
imgui = { version = "0.8.0" }

[target.'cfg(windows)'.build-dependencies]
winapi = { version = "0.3", features = ["d3dcompiler"] }

[dev-dependencies]
image = "0.23"
imgui-winit-support = "0.8.0"
glutin = "0.27.0"
old_school_gfx_glutin_ext = "0.27.0"
gfx_device_gl = "0.16"
